/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.spotbugs)
    checkstyle
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("libs")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(files("libs/algs4.jar"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Exclude .idea files from compilation
sourceSets {
    main {
        java {
            exclude("**/.idea/**")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass = "App"
}

// Custom tasks for running different assignments
tasks.register<JavaExec>("runPercolation") {
    group = "application"
    description = "Run Percolation class"
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("algorithms_1.percolation.Percolation")
}

tasks.register<JavaExec>("runPercolationStats") {
    group = "application"
    description = "Run PercolationStats class"
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("algorithms_1.percolation.PercolationStats")
    args("10", "20") // Example: 20 trials on 10x10 grid
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// SpotBugs configuration
spotbugs {
    ignoreFailures.set(true)  // Don't fail build on SpotBugs issues during development
    showStackTraces.set(true)
    showProgress.set(true)
    effort.set(com.github.spotbugs.snom.Effort.DEFAULT)
    reportLevel.set(com.github.spotbugs.snom.Confidence.DEFAULT)
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask> {
    reports.create("html") {
        required.set(true)
        outputLocation.set(file("${layout.buildDirectory.get()}/reports/spotbugs/${name}.html"))
        setStylesheet("fancy-hist.xsl")
    }
}

// Checkstyle configuration
checkstyle {
    toolVersion = "10.12.4"
    configFile = file("${rootProject.projectDir}/checkstyle.xml")
    isIgnoreFailures = true  // Don't fail build on Checkstyle issues during development
    isShowViolations = true
    maxWarnings = 0
    maxErrors = 0
}

tasks.withType<Checkstyle> {
    reports {
        xml.required.set(false)
        html.required.set(true)
        html.outputLocation.set(file("${layout.buildDirectory.get()}/reports/checkstyle/${name}.html"))
    }
}
